const { test, expect } = require('@playwright/test');
const DeliveryOrderPage = require('../../pages/DeliveryOrderPage');
const VendorReturnAuthorizationPage = require('../../pages/VendorReturnAuthorizationPage');

// Delivery Order departs from the standard document pattern used by the
// rest of the checklist:
//   - No standalone "Add" flow exists (the list's "+" only creates a saved
//     view). Records are generated by triggering "Delivery" on an Approved
//     Vendor Return Authorization.
//   - There is no Submit/Accept/Reject approval workflow, so the whole
//     Approval Flow section (TC04/TC05/TC016/TC017) is skipped entirely.
//   - Lifecycle is a fulfillment-stage progression instead: Picked -> Packed
//     -> Dispatched -> Delivered, via the Status field in Edit mode and the
//     "Validate" button on the view page.
//   - Vendor/Agreement/Currency/Entity/Location/Purchase Representative are
//     inherited from the source VRA and rendered disabled in Edit mode.
// TC01 is therefore adapted into a "record is generated correctly" case
// rather than a literal create-and-save-draft case, and TC06+ covers the
// module-specific status lifecycle.

const FIXTURE_APPROVED_VRA_VIEW_URL = '/dashboard/procurement/vendor-returns/114/view-vendor-returns';

test.describe.serial('Delivery Order - Generation & Core Fields (TC01-TC03)', () => {
  let page;
  let dop;
  let createdId;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    dop = new DeliveryOrderPage(page);
  });

  test.afterAll(async () => {
    await page.close();
  });

  test('TC01 (adapted) - Delivery Order is auto-created in Picked status from an Approved VRA', async () => {
    await dop.createFromApprovedVra(FIXTURE_APPROVED_VRA_VIEW_URL);
    await dop.gotoList();
    // Capture the newest row's ID rather than assuming row order.
    const idCell = page.locator('tbody tr').first().locator('td').nth(1);
    createdId = (await idCell.innerText()).replace(/[^0-9]/g, '') || (await idCell.innerText());
    expect(createdId).toBeTruthy();
  });

  test('TC02 (adapted) - Edit the record and persist changes to editable fields', async () => {
    await dop.gotoEdit(createdId);
    await dop.resetDateToToday();
    await dop.setReferenceNo('AUTO-DO-TC02');
    await dop.setNarration('Automation Delivery Order TC02 edit');
    await dop.save();

    await dop.gotoView(createdId);
    expect(await dop.getFieldValueOnView('Reference No.')).toBe('AUTO-DO-TC02');
    expect(await dop.getFieldValueOnView('Narration')).toBe('Automation Delivery Order TC02 edit');
  });

  test('TC03 - View page displays all previously filled data correctly', async () => {
    await dop.gotoView(createdId);
    expect(await dop.getFieldValueOnView('Vendor')).toContain('Royal Mine Industries');
    expect(await dop.getFieldValueOnView('Return Authorization')).toContain('114');
    const status = await dop.getStatusBadge();
    expect(status).toMatch(/Picked/i);
  });
});

test.describe.serial('Delivery Order - Edit Integrity (TC011/TC012/TC013)', () => {
  let page;
  let dop;
  const id = '71'; // existing fixture record (DLO-2026-000071), Picked status

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    dop = new DeliveryOrderPage(page);
  });

  test.afterAll(async () => {
    await page.close();
  });

  test('TC011 - Auto-filled fields on Edit match the View page', async () => {
    await dop.gotoView(id);
    const viewVendor = await dop.getFieldValueOnView('Vendor');
    const viewCurrency = await dop.getFieldValueOnView('Currency');
    const viewLocation = await dop.getFieldValueOnView('Location');

    await dop.gotoEdit(id);
    const editVendor = await dop.getDisabledFieldValue('Vendor');
    const editCurrency = await dop.getDisabledFieldValue('Currency');
    const editLocation = await dop.getDisabledFieldValue('Location');

    expect(editVendor).toContain(viewVendor);
    expect(editCurrency).toContain(viewCurrency);
    expect(editLocation).toContain(viewLocation);
  });

  test('TC012 - Read-only inherited fields stay read-only in Edit mode', async () => {
    await dop.gotoEdit(id);
    await expect(page.getByLabel('ID', { exact: true })).toBeDisabled();
    await expect(page.getByLabel('Return Authorization', { exact: true })).toBeDisabled();
    await expect(page.getByLabel('Vendor', { exact: true })).toBeDisabled();
    await expect(page.getByLabel('Agreement', { exact: true })).toBeDisabled();
    await expect(page.getByLabel('Currency', { exact: true })).toBeDisabled();
    await expect(page.getByLabel('Entity', { exact: true })).toBeDisabled();
    await expect(page.getByLabel('Location', { exact: true })).toBeDisabled();
    await expect(page.getByLabel('Purchase Representative', { exact: true })).toBeDisabled();
  });

  test('TC013 - Editing a single field and saving updates only that field', async () => {
    await dop.gotoEdit(id);
    await dop.resetDateToToday();
    const beforeVendor = await dop.getDisabledFieldValue('Vendor');
    const beforeCurrency = await dop.getDisabledFieldValue('Currency');

    await dop.setReferenceNo('single-field-change-do');
    await dop.save();

    await dop.gotoView(id);
    expect(await dop.getFieldValueOnView('Reference No.')).toBe('single-field-change-do');
    expect(await dop.getFieldValueOnView('Vendor')).toContain(beforeVendor);
    expect(await dop.getFieldValueOnView('Currency')).toContain(beforeCurrency);
  });
});

test.describe.serial('Delivery Order - Delete & Related Data (TC014/TC019)', () => {
  let page;
  let dop;
  let newId;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    dop = new DeliveryOrderPage(page);
    await dop.createFromApprovedVra(FIXTURE_APPROVED_VRA_VIEW_URL);
    await dop.gotoList();
    const idCell = page.locator('tbody tr').first().locator('td').nth(1);
    newId = await idCell.innerText();
  });

  test.afterAll(async () => {
    await page.close();
  });

  test('TC014 - Delete a Picked-status Delivery Order', async () => {
    await dop.gotoView(newId);
    await dop.deleteFromView();
    await dop.gotoView(newId);
    await expect(page.getByText(/not found|error/i)).toBeVisible();
  });

  test('TC019 - Related Vendor Return Authorization remains intact after delete', async () => {
    const vra = new VendorReturnAuthorizationPage(page);
    await vra.gotoView('114');
    const badges = await vra.getStatusBadges();
    expect(badges.join(' ')).toMatch(/Approved/i);
  });
});

test.describe.serial('Delivery Order - Status Lifecycle (module-specific, TC06)', () => {
  let page;
  let dop;
  const id = '69'; // fixture record currently in Picked status (DLO-2026-000069)

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    dop = new DeliveryOrderPage(page);
  });

  test.afterAll(async () => {
    await page.close();
  });

  test('TC06a - Attempting to skip a stage (Picked -> Packed via direct select) is blocked', async () => {
    await dop.gotoEdit(id);
    await dop.openStatusDropdown();
    // "Packed" rendered visually disabled in the dropdown while current
    // stage is "Picked" - clicking it should not change the selection.
    const isDisabled = await dop.isStatusOptionDisabled('Packed');
    expect(isDisabled).toBeTruthy();
  });

  test('TC06b - "Validate" advances the stage by one step on the view page', async () => {
    await dop.gotoView(id);
    const before = await dop.getStatusBadge();
    expect(before).toMatch(/Picked/i);

    await dop.clickValidate();
    await dop.gotoView(id);
    const after = await dop.getStatusBadge();
    expect(after).not.toBe(before);
  });
});

test.describe('Delivery Order - Listing Page (TC-L01-05)', () => {
  test('TC-L01 - Search/filter the list', async ({ page }) => {
    const dop = new DeliveryOrderPage(page);
    await dop.gotoList();
    await dop.searchList('DLO-2026-000071');
    await expect(page.getByText('DLO-2026-000071')).toBeVisible();

    await dop.searchList('no-such-delivery-order-xyz');
    await expect(dop.noDataRow()).toBeVisible();
  });

  test('TC-L02 - Sort a column ascending/descending', async ({ page }) => {
    const dop = new DeliveryOrderPage(page);
    await dop.gotoList();
    const dateHeader = dop.columnHeader('Date');
    await expect(dateHeader).toHaveAttribute('aria-sort', 'none');
    await dateHeader.click();
    await expect(dateHeader).toHaveAttribute('aria-sort', 'ascending');
    await dateHeader.click();
    await expect(dateHeader).toHaveAttribute('aria-sort', 'descending');
  });

  test('TC-L03 - Paginate between pages', async ({ page }) => {
    const dop = new DeliveryOrderPage(page);
    await dop.gotoList();
    const before = await dop.getPaginationLabel();
    await dop.nextPageButton().click();
    expect(await dop.getPaginationLabel()).not.toBe(before);
    await dop.prevPageButton().click();
  });

  test('TC-L04 - Row action menu shows only status-appropriate actions', async ({ page }) => {
    const dop = new DeliveryOrderPage(page);
    await dop.gotoList();
    const firstRow = page.locator('tbody tr').first();
    await firstRow.locator('[aria-label="More Icon"], td:first-child').first().click();
    await expect(page.getByRole('menuitem', { name: 'Edit' })).toBeVisible();
    await expect(page.getByRole('menuitem', { name: 'Duplicate' })).toHaveCount(0);
  });

  test('TC-L05 - Row status badge matches Picked/Delivered lifecycle state', async ({ page }) => {
    const dop = new DeliveryOrderPage(page);
    await dop.gotoList();
    await expect(page.getByText('Picked').first()).toBeVisible();
    await expect(page.getByText('Delivered').first()).toBeVisible();
  });
});

test.describe('Delivery Order - Field Validations (TC-V01/TC-V02)', () => {
  test('TC-V01 - Required Date field cannot be cleared and saved', async ({ page }) => {
    const dop = new DeliveryOrderPage(page);
    await dop.gotoEdit('71');
    await page.getByLabel('Date', { exact: true }).fill('');
    await dop.save();
    await expect(page.getByText(/required|invalid date/i)).toBeVisible();
  });

  test('TC-V02 - Invalid Exchange Rate format is rejected', async ({ page }) => {
    const dop = new DeliveryOrderPage(page);
    await dop.gotoEdit('71');
    await dop.setExchangeRate('abc');
    await dop.save();
    await expect(page.getByText(/must be a number|invalid/i)).toBeVisible();
  });
});
